//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UTTT.Ejemplo.Persona.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int id { get; set; }
        public int idComPersona { get; set; }
        public string strNombreUsuario { get; set; }
        public string strContraseña { get; set; }
        public int idCatEstadoUser { get; set; }
        public System.DateTime dteFechaRegistro { get; set; }
        public string token { get; set; }
    
        public virtual CatEstadoUser CatEstadoUser { get; set; }
        public virtual Persona Persona { get; set; }
    }
}
